spring:
  application:
    name: eureka-client-provider

server:
  port: 8762

eureka:
  instance:
    # 心跳间隔
    lease-renewal-interval-in-seconds: 5
    # 没有心跳的淘汰时间
    lease-expiration-duration-in-seconds: 10

  client:
    # 定时刷新本地缓存时间
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://192.168.0.100:8761/eureka




