spring:
  application:
    name: eureka-client-consumer-feign

server:
  port: 8764

eureka:
  client:
    service-url:
      defaultZone: http://10.0.17.164:8761/eureka/,http://10.0.23.143:8761/eureka


